openapi: 3.0.0
info:
  title: Generic eSIM Provider API
  version: 1.0.0
  description: Defines the common interface for ordering and retrieving eSIMs from a third-party provider.
servers:
  - url: https://api.{provider}.com/v1
paths:
  /esims/order:
    post:
      summary: Order a new eSIM
      operationId: orderEsim
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - customerEmail
                - customerReference
              properties:
                productId:
                  type: string
                  description: The unique identifier for the eSIM product to be ordered.
                  example: "product-eu-5gb-7d"
                customerEmail:
                  type: string
                  format: email
                  description: The customer's email address for order confirmation or direct delivery (if supported).
                  example: "customer@example.com"
                customerReference:
                  type: string
                  description: An optional reference ID from the calling system (e.g., our order ID).
                  example: "NR-ORDER-12345"
      responses:
        '200':
          description: eSIM order placed successfully.
          content:
            application/json:
              schema:
                type: object
                required:
                  - orderId
                  - status
                  - esimDetails
                properties:
                  orderId:
                    type: string
                    description: The provider's internal order ID for the eSIM.
                    example: "provider-order-XYZ"
                  status:
                    type: string
                    enum: ["PENDING", "ACTIVE", "COMPLETED", "FAILED"]
                    description: The current status of the eSIM order.
                    example: "PENDING"
                  esimDetails:
                    type: object
                    description: Details about the issued eSIM, if available immediately.
                    properties:
                      lpaCode:
                        type: string
                        description: Local Profile Assistant (LPA) activation code.
                        example: "LPA:1$SM-DP-A-001.GSMA.COM$ABCDEFG"
                      qrCode:
                        type: string
                        description: Base64 encoded QR code image data or URL to QR code.
                        example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
                      iccid:
                        type: string
                        description: Integrated Circuit Card Identifier.
                        example: "89882200000000000000000000000000"
        '400':
          description: Invalid request payload.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                  message:
                    type: string
        '401':
          description: Unauthorized - invalid API key.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                  message:
                    type: string
        '500':
          description: Internal server error at the provider.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                  message:
                    type: string
  /esims/status/{orderId}:
    get:
      summary: Get eSIM order status
      operationId: getEsimStatus
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
          description: The provider's internal order ID for the eSIM.
          example: "provider-order-XYZ"
      responses:
        '200':
          description: eSIM order status retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                required:
                  - orderId
                  - status
                  - esimDetails
                properties:
                  orderId:
                    type: string
                    description: The provider's internal order ID for the eSIM.
                    example: "provider-order-XYZ"
                  status:
                    type: string
                    enum: ["PENDING", "ACTIVE", "COMPLETED", "FAILED", "CANCELLED"]
                    description: The current status of the eSIM order.
                    example: "COMPLETED"
                  esimDetails:
                    type: object
                    description: Details about the issued eSIM, if available.
                    properties:
                      lpaCode:
                        type: string
                        description: Local Profile Assistant (LPA) activation code.
                        example: "LPA:1$SM-DP-A-001.GSMA.COM$ABCDEFG"
                      qrCode:
                        type: string
                        description: Base64 encoded QR code image data or URL to QR code.
                        example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
                      iccid:
                        type: string
                        description: Integrated Circuit Card Identifier.
                        example: "89882200000000000000000000000000"
        '404':
          description: Order not found.
        '500':
          description: Internal server error at the provider.