openapi: 3.0.0
info:
  title: Google Sheets eSIM Dispatch API
  version: 1.0.0
  description: Defines the interaction for dispatching eSIM details by appending rows to a Google Sheet.
servers:
  - url: https://sheets.googleapis.com/v4/spreadsheets
paths:
  /{spreadsheetId}/values/{range}:
    post:
      summary: Append values to a Google Sheet
      operationId: appendSheetValues
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the Google Spreadsheet.
          example: "1Bxc0...your_sheet_id...Y_uT"
        - name: range
          in: path
          required: true
          schema:
            type: string
          description: The A1 notation of a range to search for a logical table of data. Values will be appended after the last row of the table.
          example: "Sheet1!A1"
        - name: valueInputOption
          in: query
          required: false
          schema:
            type: string
            enum: ["RAW", "USER_ENTERED"]
            default: "RAW"
          description: How the input data should be interpreted.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - values
              properties:
                range:
                  type: string
                  description: The A1 notation of the range to which values will be appended.
                  example: "Sheet1!A1:C"
                majorDimension:
                  type: string
                  enum: ["ROWS", "COLUMNS"]
                  default: "ROWS"
                  description: The dimension that the values are grouped by.
                values:
                  type: array
                  description: The data to be written, as an array of arrays. Each inner array represents a row.
                  items:
                    type: array
                    items:
                      type: string # Assuming string for simplicity, can be more specific
                  example:
                    - ["order_id", "customer_email", "esim_qr_code"]
                    - ["NR-ORDER-123", "customer@example.com", "LPA:1$SM-DP-A-001.GSMA.COM$ABCDEFG"]
      responses:
        '200':
          description: Values appended successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  spreadsheetId:
                    type: string
                  tableRange:
                    type: string
                  updates:
                    type: object
                    properties:
                      spreadsheetId:
                        type: string
                      updatedRange:
                        type: string
                      updatedRows:
                        type: integer
                      updatedColumns:
                        type: integer
                      updatedCells:
                        type: integer
        '400':
          description: Bad Request - invalid range or values.
        '401':
          description: Unauthorized - authentication required.
        '403':
          description: Permission denied.
        '500':
          description: Internal server error.
security:
  - googleOauth2:
      - https://www.googleapis.com/auth/spreadsheets
components:
  securitySchemes:
    googleOauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/spreadsheets: Read and write access to spreadsheets.
            https://www.googleapis.com/auth/spreadsheets.readonly: Read-only access to spreadsheets.